######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 16:30:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += etsgame.h gameobject.h
FORMS += etsgame.ui
SOURCES += etsgame.cpp gameobject.cpp main.cpp