######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 4 10:36:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += etsgame.h gameobject.h
FORMS += etsgame.ui
SOURCES += etsgame.cpp gameobject.cpp main.cpp
RESOURCES += images.qrc
