######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 28 16:33:52 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += etsgame.h gameobject.h
FORMS += etsgame.ui
SOURCES += etsgame.cpp gameobject.cpp main.cpp
